version: 2
updates:
  - package-ecosystem: npm
    directory: "/app/experimenter/static/rapid"
    schedule:
      interval: weekly
    target-branch: dependencies
  - package-ecosystem: npm
    directory: "/app/experimenter/static/core"
    schedule:
      interval: weekly
    target-branch: dependencies
  - package-ecosystem: pip
<<<<<<< HEAD
    directory: "/app/experiments/tests/integration/"
=======
    directory: "/app/tests/"
>>>>>>> e11b3e69... temp
    schedule:
      interval: weekly
    target-branch: dependencies
  - package-ecosystem: pip
    directory: "/app"
    schedule:
      interval: weekly
    target-branch: dependencies
